In [1]:
msp = "path to the million song dataset subset"

In [2]:
import eda.hdf5_getters as getters
import matplotlib.pyplot as plt
import numpy as np
import os
import glob
import pandas as pd
import get_metric
import json

In [12]:
# loops through all hdf5 files in the subset, and applies getters to each file, and creates a pandas dataframe
# currently reads in track_id, timbre, and pitch, but you can change this yourself

# the last decode line is to decode byte strings into literal strings

root = msp
pattern = "*.h5"

infos = []
i = 0
for root, dirs, files in os.walk(msp):
    files = glob.glob(os.path.join(root, pattern))
    for f in files:
        song = []
        # print(f)
        # break
        h5 = getters.open_h5_file_read(f)
        # print(i)
        song.append(getters.get_track_id(h5))
        # song.append(getters.get_artist_name(h5))
        # song.append(getters.get_title(h5))
        song.append(getters.get_segments_timbre(h5))
        # song.append(getters.get_segments_loudness_max(h5))
        song.append(getters.get_segments_pitches(h5))
        # song.append(getters.get_segments_confidence(h5))
        infos.append(song)
        i += 1
        if i == 100:
            break

info_df = pd.DataFrame(data = infos, columns = ['track_id', 'timbre', 'pitch'])
info_df['track_id'] = info_df['track_id'].transform(lambda x: x.decode())

[[b'TRARRZU128F4253CA2',
  array([[   0.   ,  171.13 ,    9.469, ...,    0.973,  -10.64 ,   -7.228],
         [   5.952,   58.337,   -9.347, ...,   19.718,   -3.724,  -13.837],
         [  14.366,   11.654,   -2.661, ...,   37.549,   23.565,   -2.136],
         ...,
         [  49.925,   63.653,    3.173, ...,   16.402,   -6.021,   -9.08 ],
         [  50.368,   64.973,   -0.426, ...,   12.364,   13.986,   18.95 ],
         [  38.181,   85.384, -120.104, ...,  -28.746, -120.982,   15.571]]),
  array([[0.726, 0.112, 0.02 , ..., 0.015, 0.074, 1.   ],
         [0.169, 0.142, 0.135, ..., 0.138, 0.12 , 0.201],
         [0.066, 0.078, 0.085, ..., 0.087, 0.024, 0.058],
         ...,
         [0.36 , 0.292, 0.066, ..., 0.04 , 0.047, 0.457],
         [0.539, 0.578, 0.15 , ..., 0.047, 0.067, 0.393],
         [0.266, 0.297, 0.144, ..., 0.041, 0.04 , 0.145]])],
 [b'TRARRJL128F92DED0E',
  array([[ 8.00000e-03,  1.70986e+02,  9.12600e+00, ...,  1.10500e+00,
          -1.07720e+01, -7.33800e+00],
   

In [14]:
info_df

track_id                                             timbre  \
0     TRARRZU128F4253CA2  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
1     TRARRJL128F92DED0E  [[0.008, 170.986, 9.126, -28.685, 57.183, -50....   
2     TRARRUZ128F9307C57  [[1.337, 145.247, -43.274, -47.807, 18.519, -4...   
3     TRARRWA128F42A0195  [[14.832, -56.33, 69.981, -43.028, 138.861, 58...   
4     TRARRPG12903CD1DE9  [[10.095, 38.901, 84.505, -190.87, 59.787, 25....   
...                  ...                                                ...   
9988  TRBBWSE128F9313963  [[12.021, 129.011, 98.485, -308.168, 44.077, -...   
9989  TRBBWDJ128F42595D5  [[24.978, 129.582, 102.42, -99.22, 65.22, 167....   
9990  TRBBWNS128F426F760  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
9991  TRBBWIP128F4287400  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
9992  TRBBWKS128F424E84A  [[0.122, 167.975, 8.743, -32.074, 58.251, -50....   

                                                  pitch  
0     [[0.726, 0.112, 0.02, 0.019, 0.01, 0.038, 0.03...  
1     [[0.943, 1.0, 0.91, 0.782, 0.726, 0.806, 0.314...  
2     [[1.0, 0.926, 0.264, 0.384, 0.298, 0.261, 0.22...  
3     [[0.835, 0.639, 0.492, 0.399, 0.326, 0.697, 0....  
4     [[0.014, 0.014, 0.246, 0.037, 0.078, 0.322, 0....  
...                                                 ...  
9988  [[0.583, 0.552, 0.338, 0.294, 0.192, 0.244, 0....  
9989  [[0.611, 0.703, 0.542, 0.747, 0.568, 0.662, 0....  
9990  [[1.0, 0.721, 0.521, 0.492, 0.384, 0.673, 0.56...  
9991  [[0.924, 0.914, 0.722, 0.897, 0.946, 0.896, 0....  
9992  [[0.976, 0.765, 0.714, 0.577, 0.553, 0.499, 0....  

[9993 rows x 3 columns]

In [15]:
song_genres = {
    'id': [],
    'genre': []
}

with open('../data/msd_tagtraum_cd2c_edited.cls', 'r') as file:
    for line in file:
        s = line.split()
        song_genres['id'].append(s[0])
        song_genres['genre'].append(s[1])
song_genres = pd.DataFrame(song_genres)
song_genres
        

id       genre
0       TRAAAAK128F9318786        Rock
1       TRAAAAW128F429D538         Rap
2       TRAAADJ128F4287B47        Rock
3       TRAAADZ128F9348C2E       Latin
4       TRAAAED128E0783FAB        Jazz
...                    ...         ...
191396  TRZZZMY128F426D7A2      Reggae
191397  TRZZZRJ128F42819AF        Rock
191398  TRZZZUK128F92E3C60        Folk
191399  TRZZZZD128F4236844        Rock
191400  TRZZZZZ12903D05E3A  Electronic

[191401 rows x 2 columns]

In [16]:
# merge the info_df with genre labels
merged_df = info_df.merge(song_genres, how = 'inner', right_on = 'id', left_on = 'track_id').drop(columns = ['id'])

In [29]:
merged_df[5:15]

track_id                                             timbre  \
5   TRARIIY128F147187D  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
6   TRARIZK128F92FF27A  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
7   TRARGLY128F935AAD5  [[31.775, 129.988, -121.649, 188.98, -35.942, ...   
8   TRARZBX12903CD70DA  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
9   TRARZBR128F934715D  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
10  TRARTEH128F423DBC1  [[21.979, 22.152, 20.974, -219.533, 56.299, 21...   
11  TRARTJL128F92CB44B  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
12  TRARTSA128F4291550  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
13  TRARTCZ128F427A176  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
14  TRARSMV128F1469CCF  [[0.013, 170.828, 9.081, -28.86, 57.195, -50.0...   

                                                pitch       genre  
5   [[1.0, 0.871, 0.806, 0.807, 0.453, 0.459, 0.58...        Rock  
6   [[0.623, 0.447, 0.349, 0.3, 0.259, 0.358, 0.66...        Rock  
7   [[0.116, 0.086, 0.111, 0.13, 0.282, 1.0, 0.257...        Rock  
8   [[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...  Electronic  
9   [[0.892, 0.421, 0.291, 0.196, 0.288, 0.615, 0....       Latin  
10  [[0.739, 0.619, 0.697, 0.598, 0.467, 0.283, 0....        Rock  
11  [[0.991, 1.0, 0.404, 0.345, 0.289, 0.292, 0.28...        Rock  
12  [[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...       Metal  
13  [[0.879, 1.0, 0.661, 0.514, 0.605, 0.964, 0.74...       Blues  
14  [[0.641, 0.506, 0.527, 0.38, 0.4, 1.0, 0.903, ...      Reggae

In [18]:
(merged_df.iloc[0]['timbre'][0])

array([  23.928, -119.362,   33.96 , -122.038,    8.715,  182.189,
        108.577,  -22.368,  -98.571,  135.408,  -28.729,   12.234])

In [ ]:
get_metric('TRARREF128F422FD96', getters.get_title), get_metric('TRARREF128F422FD96', getters.get_artist_name)

(b'Halloween', b'Dead Kennedys')

In [23]:
fig = pd.DataFrame(merged_df.iloc[0]['timbre']).plot(kind = 'line', title = 'Timbre for a "Halloween" by Dead Kennedys (Genre: Punk)')
fig#.write_image('/Users/hiro002/shazam-2.0/so/halloween-timbre.png')

In [27]:
pd.DataFrame(merged_df.iloc[0]['pitch']).plot(kind = 'line', title = 'Pitch for a "Punk" Song 1')

In [24]:
get_metric('TRBBYOI128F4256732', getters.get_title), get_metric('TRBBYOI128F4256732', getters.get_artist_name)

(b'Out Of This World', b'Black Flag')

In [25]:
pd.DataFrame(merged_df.iloc[2245]['timbre']).plot(kind = 'line', title = 'Timbre for a "Out Of This World" by Black Flag (Genre: Punk)')

In [27]:
get_metric('TRBBYFJ128F42A22D4', getters.get_title), get_metric('TRBBYFJ128F42A22D4', getters.get_artist_name)

(b'Jingle Bells', b'Jim Reeves')

In [28]:
pd.DataFrame(merged_df.iloc[2247]['timbre']).plot(kind = 'line', title = 'Timbre for a "Jingle Bells" by Jim Reeves (Genre: Country)')

In [30]:
get_metric('TRARZBX12903CD70DA', getters.get_title), get_metric('TRARZBX12903CD70DA', getters.get_artist_name)

(b'Cavalleria Rusticana', b'William Orbit')

In [32]:
pd.DataFrame(merged_df.iloc[8]['timbre']).plot(kind = 'line', title = 'Timbre for a "Cavalleria Rusticana" by William Orbit (Genre: Electronic)')

In [ ]:
# save this csv 

info_df.to_csv('msd_genre.csv')

In [97]:
df = pd.read_csv('msd_genre.csv')

In [99]:
# we need to call json.loads becuase when saving as csv, arrays become conveted to strings

df['timbre'] = df['timbre'].transform(json.loads)
df['pitch'] = df['pitch'].transform(json.loads)
df = df.drop(columns = ['Unnamed: 0'])

In [103]:
df

track_id                                             timbre  \
0     TRARREF128F422FD96  [[23.928, -119.362, 33.96, -122.038, 8.715, 18...   
1     TRARUOP12903CF2384  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
2     TRARUHU128F92FDC00  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
3     TRARUTP128E0797FC7  [[3.735, 85.777, -26.167, -61.262, 81.751, -20...   
4     TRARIRG128F147FC96  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
...                  ...                                                ...   
2244  TRBBYYL128F4236EBC  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
2245  TRBBYOI128F4256732  [[0.102, 168.868, 6.486, -31.413, 55.144, -50....   
2246  TRBBYDT128F14805B4  [[33.671, 84.55, 202.282, 2.574, 46.344, 64.34...   
2247  TRBBYFJ128F42A22D4  [[0.0, 171.13, 9.469, -28.48, 57.491, -50.067,...   
2248  TRBBWDJ128F42595D5  [[24.978, 129.582, 102.42, -99.22, 65.22, 167....   

                                                  pitch    genre  
0     [[0.146, 0.203, 0.219, 0.209, 0.172, 0.123, 0....     Punk  
1     [[0.937, 0.557, 0.215, 0.198, 0.112, 0.135, 0....    Metal  
2     [[1.0, 0.284, 0.224, 0.217, 0.245, 0.285, 0.38...      Rap  
3     [[0.121, 1.0, 0.105, 0.015, 0.016, 0.02, 0.011...     Rock  
4     [[0.819, 0.683, 0.6, 0.67, 0.291, 0.274, 0.689...      Pop  
...                                                 ...      ...  
2244  [[0.577, 0.364, 0.529, 0.674, 0.385, 0.337, 0....      Rap  
2245  [[0.345, 0.254, 0.161, 0.162, 0.25, 0.542, 0.3...     Punk  
2246  [[0.521, 0.515, 0.559, 0.631, 0.818, 0.722, 0....     Rock  
2247  [[1.0, 0.923, 0.508, 0.49, 0.511, 0.522, 0.548...  Country  
2248  [[0.611, 0.703, 0.542, 0.747, 0.568, 0.662, 0....     Rock  

[2249 rows x 4 columns]